// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7YpZzvFl18EvdwTagv0Jdh3moauD-lN4',
    appId: '1:26134867441:web:925d869fc2672b0ef92850',
    messagingSenderId: '26134867441',
    projectId: 'game-arena-e77d2',
    authDomain: 'game-arena-e77d2.firebaseapp.com',
    storageBucket: 'game-arena-e77d2.firebasestorage.app',
    measurementId: 'G-Q5X74VFKQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuXfTYhCewFHvQBnVIApUkWSXjWrEIs88',
    appId: '1:26134867441:android:12a3295454845857f92850',
    messagingSenderId: '26134867441',
    projectId: 'game-arena-e77d2',
    storageBucket: 'game-arena-e77d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp8CNhHIAu05htRqfCPmu1QloMACbtsDs',
    appId: '1:26134867441:ios:518bf8effe55af9ef92850',
    messagingSenderId: '26134867441',
    projectId: 'game-arena-e77d2',
    storageBucket: 'game-arena-e77d2.firebasestorage.app',
    androidClientId:
        '26134867441-fagfm8da6f6mats750aeiqul0oi3kk69.apps.googleusercontent.com',
    iosClientId:
        '26134867441-r3eq3ca5hmc7jglr0jec8pcka2tu4n54.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamearenaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp8CNhHIAu05htRqfCPmu1QloMACbtsDs',
    appId: '1:26134867441:ios:518bf8effe55af9ef92850',
    messagingSenderId: '26134867441',
    projectId: 'game-arena-e77d2',
    storageBucket: 'game-arena-e77d2.firebasestorage.app',
    androidClientId:
        '26134867441-fagfm8da6f6mats750aeiqul0oi3kk69.apps.googleusercontent.com',
    iosClientId:
        '26134867441-r3eq3ca5hmc7jglr0jec8pcka2tu4n54.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamearenaNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7YpZzvFl18EvdwTagv0Jdh3moauD-lN4',
    appId: '1:26134867441:web:9b7cfda2e0944af7f92850',
    messagingSenderId: '26134867441',
    projectId: 'game-arena-e77d2',
    authDomain: 'game-arena-e77d2.firebaseapp.com',
    storageBucket: 'game-arena-e77d2.firebasestorage.app',
    measurementId: 'G-FBJE3W3CW7',
  );
}
